# Generated by Django 5.0.4 on 2024-07-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='is_magical',
            field=models.BooleanField(default=False),
        ),
    ]
